//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBlibraryTH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.ToolBookings = new HashSet<ToolBooking>();
        }
    
        public int CusID { get; set; }
        public string CusName { get; set; }
        public string CusStreet { get; set; }
        public string CusTown { get; set; }
        public string CusCity { get; set; }
        public string CusPostcode { get; set; }
        public string CusTelephone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolBooking> ToolBookings { get; set; }
    }
}
